# Generated by Django 5.0.6 on 2024-07-06 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0003_snack_image_alter_movieorder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorder',
            name='snack',
        ),
        migrations.AddField(
            model_name='movieorder',
            name='snacks',
            field=models.ManyToManyField(to='Cinema.snackorder'),
        ),
        migrations.AlterField(
            model_name='movieorder',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 6)),
        ),
        migrations.AlterField(
            model_name='snackorder',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 6)),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 6)),
        ),
    ]
